### ISSUE TITLE
running supabase functions serve fails. running supabase functions serve <name> causes postgres connection to fail

### ISSUE THREAD

**Issue by oldbettie** [supabase/edge-runtime#115]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
seems like there is an issue with a `deno` package when running ` supabase functions serve` I get this following error.

```
worker "/home/deno/functions/scraper" returned an error: Uncaught SyntaxError: The requested module '/v125/jszip@3.5.0/esnext/lib/readable-stream-browser.js' does not provide an export named 'default'
    at https://esm.sh/v125/jszip@3.5.0/esnext/jszip.mjs:2:291
InvalidWorkerCreation: worker boot error
    at async Function.create (ext:sb_user_workers/user_workers.js:80:21)
    at async Server.<anonymous> (file:///home/deno/main/index.ts:95:24)
    at async Server.#respond (https://deno.land/std@0.182.0/http/server.ts:220:24)
```

if I run `supabase functions serve <function-name> --env-file supabase/.env` then it will work once but needs to be restarted after every run.

seems to only be when done locally. which makes it incrediby frustrating to have to deploy changes everytime we want to test a function.

## To Reproduce
start supabase and run `supabase functions serve`

## Expected behavior
the functions should work

the function should execute and hot reload locally as expected. deno seems to be flawed 

## System information

- OS: Ventura 13.4
- Browser chrome
- Version of supabase-js: 1.68.6
- Version of Node.js: 20.3.0

## Additional context
seems like local lambda is still quite buggy.

**Comment by laktek** [comment]
@gregnr Did the import work when function was deployed to Deno Deploy? Will try to reproduce it.

**Comment by oldbettie** [comment]
everything worked fine when deployed to supabase I am not importing anything for JSZip it seems to be something done under the hood. Should I be cloning and running my functions in the edge-runtime rather then the supabase cli?

**Comment by northfacejmb** [comment]
I think I might be having a similar issue. Thank you for posting, I hope you're able to get to the bottom of it

**Comment by gregnr** [comment]
@laktek sorry I didn't actually attempt on Deno Deploy - was making that assumption based on the original post, but I could be wrong.

@oldbettie the latest Supabase CLI uses `edge-runtime` under the hood when you run `supabase functions serve`.

> I am not importing anything for JSZip it seems to be something done under the hood
Do you mind sharing the code you are running? Guessing you have another dependency that imports JSZip.

**Comment by oldbettie** [comment]
```
{
  "imports": {
    "postgres": "https://deno.land/x/postgres@v0.17.0/mod.ts",
    "puppeteer": "https://deno.land/x/puppeteer@16.2.0/mod.ts"
  }
}
{
  "imports": {
    "postgres": "https://deno.land/x/postgres@v0.17.0/mod.ts",
    "puppeteer": "https://deno.land/x/puppeteer@16.2.0/mod.ts"
  }
}
```
here is my import map. I am alse importing serve directly into the functions as it seemed to be a bit faster

**Comment by gregnr** [comment]
Thanks. Looks like `puppeteer` is likely the one importing JSZip:
https://github.com/lucacasonato/deno-puppeteer/blob/45b3162585b98ad8d54abeb56f48ecbb17c614eb/vendor/puppeteer-core/vendor/zip/mod.ts#L1

You can try [overriding imports](https://deno.com/manual@v1.34.3/basics/import_maps#overriding-imports) to force `puppeteer` to pull in JSZip with the `bundle` param (untested):

```json
{
  "imports": {
    "postgres": "https://deno.land/x/postgres@v0.17.0/mod.ts",
    "puppeteer": "https://deno.land/x/puppeteer@16.2.0/mod.ts"
  },
  "scopes": {
    "puppeteer": {
      "https://esm.sh/jszip@3.5.0/": "https://esm.sh/jszip@3.5.0?bundle"
    }
  }
}
```

**Comment by Elodin77** [comment]
I am also experiencing this exact issue. I'm following the example for puppeteer used in the documentation https://supabase.com/docs/guides/functions/examples/screenshots. 
I tried to override the imports so my `import_map.json` looks like:
```
{
  "imports": {
    "std/server": "https://deno.land/std@0.177.0/http/server.ts",
    "puppeteer": "https://deno.land/x/puppeteer@16.2.0/mod.ts"
  },
  "scopes": {
    "puppeteer": {
      "https://esm.sh/jszip@3.5.0/": "https://esm.sh/jszip@3.5.0?bundle/"
    }
  }
}
```
However this had no effect, same error.

**Comment by gregnr** [comment]
Okay found some time to test this out - I was able to get it working using this import map:
```json
{
  "imports": {
    "postgres": "https://deno.land/x/postgres@v0.17.0/mod.ts",
    "puppeteer": "https://deno.land/x/puppeteer@16.2.0/mod.ts"
  },
  "scopes": {
    "https://deno.land/x/puppeteer@16.2.0/vendor/puppeteer-core/vendor/zip/mod.ts": {
      "https://esm.sh/jszip@3.5.0": "https://esm.sh/jszip@3.5.0?bundle"
    }
  }
}
```

Or if you just want to override `jszip` everywhere:
```json
{
  "imports": {
    "postgres": "https://deno.land/x/postgres@v0.17.0/mod.ts",
    "puppeteer": "https://deno.land/x/puppeteer@16.2.0/mod.ts",
    "https://esm.sh/jszip@3.5.0": "https://esm.sh/jszip@3.5.0?bundle"
  }
}
```

Worth noting this is a workaround - ideally we find out what's really happening here and see what is different between `edge-runtime` and Deno.

**Comment by andreespirela** [comment]
```
andrespirela@Andress-MBP edge-runtime % deno run --allow-all examples/empty-response/index.ts
error: Uncaught SyntaxError: The requested module '/v125/jszip@3.5.0/esnext/lib/readable-stream-browser.js' does not provide an export named 'default'
    at <anonymous> (https://esm.sh/v125/jszip@3.5.0/esnext/jszip.mjs:2:291)
```

@laktek 
- This import issue also happens on the latest version of Deno.
- https://esm.sh/v125/jszip@3.5.0/esnext/lib/readable-stream-browser.js shows there is not default imports even though the code is trying to access a default module which is why the error is being thrown.

**Comment by skikrumb-ryan** [comment]
Also getting this issue which works on a different project. Went back and used the same function I wrote on another project and I get this error when trying to serve:

`Could not resolve './models/EmailJSResponseStatus' from 'file:///tmp/sb-compile-edge-runtime/node_modules/localhost/@emailjs/nodejs/4.0.4/mjs/index.js'.
An error has occured
InvalidWorkerCreation: worker boot error Could not resolve './models/EmailJSResponseStatus' from 'file:///tmp/sb-compile-edge-runtime/node_modules/localhost/@emailjs/nodejs/4.0.4/mjs/index.js'.
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:144:15)
`

**Comment by AliBdeir** [comment]
It's been almost a year. Is there really no official response or at least acknowledgment of this?

**Comment by nyannyacha** [comment]
I've tried to reproduce this issue again, but I couldn't.
It seems that there has been a change in the import statement for the `readable-stream` returned by `esm.sh/v125/jszip@3.5.0`.

```typescript
// https://esm.sh/v125/jszip@3.5.0 (22 Aug 2025)

/* esm.sh - jszip@3.5.0 */
import "/v125/lie@3.3.0/denonext/lie.mjs";
import "/v125/readable-stream@2.3.8/denonext/readable-stream.mjs"; // 👈
import "/v125/set-immediate-shim@1.0.1/denonext/set-immediate-shim.mjs";
import "/v125/pako@1.0.11/denonext/pako.mjs";
export * from "/v125/jszip@3.5.0/denonext/jszip.mjs";
export { default } from "/v125/jszip@3.5.0/denonext/jszip.mjs";
```

At the time this issue was discussed, I assume that the import path was `v125/jszip@3.5.0/esnext/lib/readable-stream-browser.js` rather than `v125/jszip@3.5.0/esnext/lib/readable-stream-browser.js`—In fact, this import path still returns an error due to the same SyntaxError mentioned above, even in the latest version.

However, `https://esm.sh/v125/jszip@3.5.0` now references `readable-stream@2.3.8/denonext/readable-stream.mjs` instead of `v125/jszip@3.5.0/esnext/lib/readable-stream-browser.js`, so this issue should be resolved at this point.

When I ran the Puppeteer example locally at this point, I confirmed that the example works perfectly except that the browserless endpoint in the example is no longer available and had to be changed to a different endpoint.

If this issue persists in the latest version of edge-runtime or supabase cli, please create a new issue.

I will close this issue.
Thank you!
