### ISSUE TITLE
Error: Module not found "https://deno.land/std@0.150.0/media_types/_util.ts".

### ISSUE THREAD

**Issue by CareTiger** [supabase/edge-runtime#132]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
```
error: Uncaught (in promise) Error: Module not found "https://deno.land/std@0.150.0/media_types/_util.ts". 
      const ret = new Error(getStringFromWasm0(arg0, arg1));                                               
                  ^                                                                                        
    at __wbg_new_8d2af00bc1e329ee (https://deno.land/x/eszip@v0.35.0/eszip_wasm.generated.js:513:19)       
    at <anonymous> (https://deno.land/x/eszip@v0.35.0/eszip_wasm_bg.wasm:1:1559899)                        
    at <anonymous> (https://deno.land/x/eszip@v0.35.0/eszip_wasm_bg.wasm:1:1398157)                        
    at <anonymous> (https://deno.land/x/eszip@v0.35.0/eszip_wasm_bg.wasm:1:1895031)                        
    at __wbg_adapter_40 (https://deno.land/x/eszip@v0.35.0/eszip_wasm.generated.js:229:6)                  
    at real (https://deno.land/x/eszip@v0.35.0/eszip_wasm.generated.js:213:14)                             
                                                                                                           
Try rerunning the command with --debug to troubleshoot the error.
Error: Process completed with exit code 1.
```

## To Reproduce

Try to deploy edge function to staging/production.

## Expected behavior

Function should deploy to staging/production without error. 

## System information

- OS: Windows 11
-
```
$ supabase --version
1.75.3
```
```
$ docker --version
Docker version 24.0.2, build cb74dfc
```
```
$ node --version
v18.16.1
```

**Comment by northfacejmb** [comment]
I had the same issue. Then for seemingly no reason, it started working.

**Comment by CareTiger** [comment]
yeah. its working again
