### ISSUE TITLE
Self-hosted edge functions - Error when importing shared local files

### ISSUE THREAD

**Issue by neuquen** [supabase/edge-runtime#149]
# Bug report

## Describe the bug

Calling an edge function that imports local files from the `_shared` directory produces the following error:
```
{"msg":"InvalidWorkerCreation: worker boot error"}
```

Within the `supabase-edge-functions` container logs I see the following error:
```
Failed to load module: "file:///home/deno/functions/_shared/message.ts" - Invalid file path.
  Specifier: file:///home/deno/functions/_shared/message.ts
```

## To Reproduce

1. Follow the steps outlined under "Running Supabase" to download supabase and run using docker: https://supabase.com/docs/guides/self-hosting/docker#running-supabase
3. Create the file `/functions/_shared/message.ts`:
```
export function message() {
  return 'Hello from Edge Functions!';
}
```
4. Update `/functions/hello/index.ts` to import the function from that file:
```
import { serve } from "https://deno.land/std@0.177.1/http/server.ts"
import { message } from "../_shared/message.ts";

serve(async () => {
  return new Response(
    `${message()}`,
    { headers: { "Content-Type": "application/json" } },
  )
})
```
5. Run `docker compose down` and `docker compose up` to ensure the new file is present within the container.
6. Issue an http request to the endpoint: `http://localhost:8000/functions/v1/hello`

## Expected behavior

I'm expecting the message `Hello from Edge Functions!` to be displayed, but instead, I see `{"msg":"InvalidWorkerCreation: worker boot error"}`

## System information

- OS: Docker container on Ubuntu 22 (EC2 on AWS)

## Additional context

If I move the `_shared` directory underneath hello: `/functions/hello/_shared/`, and alter the import statement within `/hello/index.ts` to `import { message } from "./_shared/message.ts";`, then it works fine.

**Comment by AndriyBas** [comment]
I have the same issue

**Comment by ginsudev** [comment]
I have this issue too

**Comment by fraktalize** [comment]
I also have this issue!

**Comment by laktek** [comment]
@ginsudev @fraktalize Are you experiencing the issue when running via Supabase CLI? Have you tried upgrading to the latest version of the CLI?

If you're running edge-runtime directly, can you share your setup so I can try to reproduce the issue.

**Comment by drobles-atdev** [comment]
having the same issue today, this is is not fixed yet.

**Comment by jb-thery** [comment]
same issue :(

**Comment by thewebbeckons** [comment]
Also same issue; just updated the CLI. 

supabase-edge-runtime-1.33.5

**Comment by laktek** [comment]
@jb-thery @thewebbeckons Are you trying to import from `_shared` directory in `supabase/functions`? What's the exact error message you get? Also, it would be handy if you can share the import statements in your function so I can try to reproduce it.

**Comment by thewebbeckons** [comment]
@laktek Seems like mine was something different just reporting the same error message. Can disregard my comment; everything is resolved on my end.

**Comment by antonio-petrov** [comment]
I have the same issue. Running 1.38.0.
_shared is in the `functions` folder

Once I moved it into the folder where the function resides, the issue got resolved.

**Comment by questicles** [comment]
I am having the same issue also. I use the same folder setup as per https://supabase.com/docs/guides/functions/quickstart#organizing-your-edge-functions

My folder structure is as so:
`
- supabase
  - functions
    - _shared
      - admin.ts 
    - my-handler-1
      - index.ts
    - my-handler-2
      - index.ts
    - import_map.json
`

My import_map.json looks like:
`
{
    "imports": {
      "@supabase": "npm:@supabase/supabase-js@2.42.4",      
      "@admin": "./_shared/admin.ts",
    }
  }
`

If I import in either of the functions index.ts files something from @admin e.g. 
`import { myFunction } from "@admin";`

I get the following error when the function is invoked:

`Using supabase-edge-runtime-1.45.2 (compatible with Deno v1.40.3)
serving the request with /home/deno/functions/my-handler-1
serving the request with /home/deno/functions/my-handler-1
failed to load 'file:///home/deno/_shared/admin.ts': Module not found "file:///home/deno/_shared/admin.ts".
An error has occured
InvalidWorkerCreation: worker boot error failed to load 'file:///home/deno/_shared/admin.ts': Module not found "file:///home/deno/_shared/admin.ts".
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:141:15)
    at async Object.handler (file:///home/deno/main/index.ts:147:22)
    at async handleHttp (ext:sb_core_main_js/js/http.js:112:15) {
  name: "InvalidWorkerCreation"
}`

Only by moving the admin.ts code into the my-handler-1 folder makes the import work, however this obviously makes it unable to be shared to my-handler-2/index.ts

**Comment by s-borah** [comment]
Same issue, please fix it or suggest solution please.

**Comment by ophelie-gaudin** [comment]
same issue here

**Comment by publicvirtualvoid** [comment]
Same issue. Is this tracked at all on the Supabase side? If this is officially not supported it really limits the usefulness of Edge Functions IMO.

**Comment by nyannyacha** [comment]
Hello everyone 😋

The problem reported by the issue owner seems to be no longer reproducible with the latest version of the CLI (or the latest version of the edge runtime image), which works fine.

So we're closing this issue for clarity.
If you are still experiencing these issues with the latest version, please open a new issue.

Thanks!

**Comment by Ge6ben** [comment]
The issue happens when running:

`deno cache --reload index.ts`

This command causes the error.

To fix it, please reinstall Deno completely and install it again without running the cache command.
In other words, after reinstalling Deno, do not run:

`deno cache --reload index.ts`
