### ISSUE TITLE
Response is not interpreted when handler function.

### ISSUE THREAD

**Issue by andreespirela** [supabase/edge-runtime#176]
# Bug report

1) It seems like the following code works under Deno deploy (https://deno.com/deploy/docs/examples) but not Edge Runtime

```
export default async function handler(req) {
    return new Response("Hello World");
}
```

2) This is causing a:
```
TypeError: request body receiver not connected (request closed)
    at Object.write (ext:deno_web/06_streams.js:954:20)
    at Module.invokeCallbackFunction (ext:deno_webidl/00_webidl.js:976:16)
    at WritableStreamDefaultController.writeAlgorithm (ext:deno_web/06_streams.js:3675:14)
    at writableStreamDefaultControllerProcessWrite (ext:deno_web/06_streams.js:4177:55)
    at writableStreamDefaultControllerAdvanceQueueIfNeeded (ext:deno_web/06_streams.js:4080:5)
    at writableStreamDefaultControllerWrite (ext:deno_web/06_streams.js:4224:3)
    at writableStreamDefaultWriterWrite (ext:deno_web/06_streams.js:4371:3)
    at Object.chunkSteps (ext:deno_web/06_streams.js:2534:17)
    at readableStreamFulfillReadRequest (ext:deno_web/06_streams.js:2376:17)
    at readableByteStreamControllerCommitPullIntoDescriptor (ext:deno_web/06_streams.js:2067:5)
```

Note that this works:
```
Deno.serve(() => new Response("Hello World"));
```

# Additional Context

- Latest `main`

**Comment by Ganitzsh** [comment]
I am experiencing a similar issue, I found a workaround for it but I'd like to understand.

When returning a Response, if the ReadableStream of the request (body) was not read, it will not write the response in the stream. So before sending any response you can use any method of the `request` that will read the `ReadableStream` and the issue will be gone.

Using a function expression or a function did not change anything for me.

**Comment by andreespirela** [comment]
Closing as invalid.
