### ISSUE TITLE
Workers are reused to serve multiple requests but terminated on timeout

### ISSUE THREAD

**Issue by olee** [supabase/edge-runtime#197]
# Bug report
- [X] I confirm this is a bug with Supabase, not with my own application. (the issue even happens with the example "hello" function provided by supabase)
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

From my understanding, when a worker is spawned it always lives for `workerTimeoutMs` to serve requests and will then be terminated.
This causes functions executing on a previously started worker to randomly fail when the timout happens while they are executed.

## To Reproduce

- Set `workerTimeoutMs` in `index.ts` to some value like 10 seconds
- Set up a simple longer running function like this:
  ```ts
  serve(async (req) => {
    await new Promise(r => setTimeout(r, 5_000));
    return new Response(`"Hello from Edge Functions!"`, { headers: { "Content-Type": "application/json" } });
  });
  ```
- Repeatedly call this function
- When a request is started eg. 8 seconds after the first one, it will crash with the following log

```
2023-10-28 01:20:45 main function started
2023-10-28 01:21:24 [Info] Listening on http://localhost:9999/
2023-10-28 01:21:24 [Info] start
2023-10-28 01:21:32 [Info] end
2023-10-28 01:21:33 [Info] start
2023-10-28 01:21:34 wall clock duration reached. isolate: 9517434353123966400
2023-10-28 01:21:34 failed to send request to user worker: connection closed before message completed
2023-10-28 01:21:34 Error: InvalidWorkerResponse: user worker failed to respond
2023-10-28 01:21:34     at async UserWorker.fetch (ext:sb_user_workers/user_workers.js:52:15)
2023-10-28 01:21:34     at async Server.<anonymous> (file:///home/deno/functions/main/index.ts:79:16)
2023-10-28 01:21:34     at async Server.#respond (https://deno.land/std@0.131.0/http/server.ts:219:24)
```

## Expected behavior

Either workers should not be reused to serve multiple requests or their timeout should reset if they receive a new request.

PS: Also, there does not seem to be a way to adjust allowed CPU-time which is also a dealbreaker for long running workers like generating AI embeddings.

**Comment by olee** [comment]
I investigated this a bit more and my only realization that the functions host is pretty much unusable to run any longer tasks or stuff that has to be executed reliably.
For now I have created a simple deno server to replace the edge-runtime.
