### ISSUE TITLE
Functions fail after "event loop error", leading to "connection was not ready"

### ISSUE THREAD

**Issue by grschafer** [supabase/edge-runtime#202]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

⚠️ ⚠️ ⚠️ **I'm using the supabase beta CLI release (1.111.1), so apologies if this issue is already known. I tried on a recent CLI version (1.108.3) which was before edge-runtime was bumped to 1.22.3 and the issue did not occur on that version.** ⚠️ ⚠️ ⚠️ 

Functions stop working after a while, after the "event loop error" message appears in the log (see repro below).

## To Reproduce

Make a new supabase project and the hello-world function and wait for ~3 minutes and all requests after that point will return a 500 response.

```
git init supabase-edgefn-conn-closed
cd supabase-edgefn-conn-closed
npx supabase@beta init
npx supabase@beta functions new hello
npx supabase@beta start
docker logs -f supabase_edge_runtime_supabase-edgefn-conn-closed

# in another shell, make a request to the edge function, which should succeed
curl -v 127.0.0.1:54321/functions/v1/hello -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0" -H "authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU" -H "content-type: application/json" --data '{"name": "world"}'

# wait ~3 minutes until you see "event loop error"
# running the curl again at this point returns a 500 server error
```

The logs from the edge-runtime container look like the below for me.

```
serving the request with /home/deno/functions/hello
[Info] Hello from Functions!

wall clock duration warning. isolate: 0496a8e5-f23d-42c4-8121-d6d314c848f2
event loop error: TypeError: Cannot convert undefined or null to object
    at slice (<anonymous>)
    at new DOMException (ext:deno_web/01_dom_exception.js:126:14)
    at [[[signalAbort]]] (ext:deno_web/03_abort_signal.js:83:14)
    at AbortController.abort (ext:deno_web/03_abort_signal.js:172:30)
    at file:///home/deno/main/index.ts:147:31
    at Object.action (ext:deno_web/02_timers.js:151:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:65:10)
    at eventLoopTick (ext:core/01_core.js:189:21)
Error in worker connection: connection closed before message completed
request failed (uri: "/hello" reason: hyper::Error(Canceled, "connection was not ready"))
```

## Expected behavior

Functions should work regardless of how long it's been since they were started or last run.

## System information

- OS: Ubuntu 22.04.03 LTS
- Supabase CLI version: 1.111.1 (beta)
- Edge-runtime docker image: public.ecr.aws/supabase/edge-runtime:v1.22.3

**Comment by grschafer** [comment]
I tested this again today using `npx supabase@v1.111.1` vs `npx supabase@v1.111.2` and this appears to be fixed in [supabase-cli v1.111.2](https://github.com/supabase/cli/releases/tag/v1.111.2) -- I no longer get the `event loop error` after ~200 seconds.
