### ISSUE TITLE
event loop error

### ISSUE THREAD

**Issue by rlee1990** [supabase/edge-runtime#259]
# Bug report
I keep getting an event loop error 

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Create a function that connects to a cloud project for supabase.
I then used import maps for StreamChat like so ```"streamchat": "npm:stream-chat@8.14.5",```
Followed their instructions and performed a function that requires await.
The function will then be called in app.
It runs without error in app but when checking the edge function logs I receive the below error.
```
event loop error: TypeError: socket.setTimeout is not a function
    at RedirectableRequest.destroyOnTimeout (file:///tmp/sb-compile-edge-runtime/node_modules/localhost/follow-redirects/1.15.5/index.js:199:12)
    at RedirectableRequest.emit (ext:deno_node/_stream.mjs:1857:11)
    at eventHandlers.<computed> (file:///tmp/sb-compile-edge-runtime/node_modules/localhost/follow-redirects/1.15.5/index.js:38:24)
    at HttpsClientRequest.emit (ext:deno_node/_stream.mjs:1857:11)
    at node:http:409:12
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:25:11)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:189:21)
```

## System information

- OS: [macOS]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [1.136.3]
- Version of Node.js: [16.15.0]

**Comment by nyannyacha** [comment]
Hi! @rlee1990 😋

What version of edge-runtime are you using? (or CLI version)
and if you could provide some reproducible code?

**Comment by nyannyacha** [comment]
Note: Based on my brief investigation, this appears to be an issue that should have been fixed since the [deno update PR](
https://github.com/supabase/edge-runtime/pull/250/files#diff-bb2679f40a8e1c15ed811a08f4d8e9288e8fa7a3ae40370d2bedb7f4225e28edR297-R300).

**Comment by rlee1990** [comment]
@nyannyacha I was using 1.39 but I tried 1.41 beta today same issue

**Comment by laktek** [comment]
@rlee1990 We have upgraded our production servers to use the latest release of Edge Runtime (which is compatible with Deno 1.39.2). Can you try invoking your functions to see if you still experience the same issue?

**Comment by rlee1990** [comment]
@laktek yes it is working now thanks.

**Comment by laktek** [comment]
@jojo699 Can you share the function code?

**Comment by jojo699** [comment]
import { serve } from "https://deno.land/std@0.177.0/http/server.ts"
import { PollyClient, SynthesizeSpeechCommand } from "https://esm.sh/@aws-sdk/client-polly@3.321.1"

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders })
  }

  try {
    const { text, voiceId } = await req.json()

    if (!text || typeof text !== "string" || text.trim() === "" || !voiceId) {
      throw new Error("Invalid or missing parameters")
    }

    const pollyClient = new PollyClient({
      region: Deno.env.get("AWS_REGION") || "",
      credentials: {
        accessKeyId: Deno.env.get("AWS_ACCESS_KEY_ID") || "",
        secretAccessKey: Deno.env.get("AWS_SECRET_ACCESS_KEY") || "",
      },
    })

    const pollyParams = {
      OutputFormat: "mp3",
      Text: text,
      TextType: "text",
      VoiceId: voiceId,
      Engine: "neural",
    }

    const pollyCommand = new SynthesizeSpeechCommand(pollyParams)
    const pollyResponse = await pollyClient.send(pollyCommand)

    if (!pollyResponse.AudioStream) {
      throw new Error("Failed to generate audio: No AudioStream in response")
    }

    const audioBuffer = await new Response(pollyResponse.AudioStream).arrayBuffer()
    const base64Audio = btoa(String.fromCharCode(...new Uint8Array(audioBuffer)))

    return new Response(JSON.stringify({ audio: base64Audio }), {
      headers: {
        ...corsHeaders,
        "Content-Type": "application/json",
      },
    })
  } catch (error) {
    console.error("Error in Test TTS function:", error)
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "An unknown error occurred" }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 500,
      },
    )
  }
})
