### ISSUE TITLE
Importing axios throws error

### ISSUE THREAD

**Issue by sweatybridge** [supabase/edge-runtime#54]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Unable to import axios from edge runtime.

## To Reproduce

- create and serve `supabase/functions/hello/index.ts`
```typescript
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import axios from "https://esm.sh/axios@1.3.5";

serve(async (req) => {
  console.log("Hello from Functions!");
  const { data } = await axios.get("https://supabase.com");
  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
});
```

- request error `curl http://localhost:54321/functions/v1/hello -X POST`
```bash
$ supabase functions serve --no-verify-jwt
Setting up Edge Functions runtime...
Serving functions on http://localhost:54321/functions/v1/<function-name>
serving the request with /home/deno/functions/hello
worker thread panicked TypeError: _.accessor is not a function
    at https://esm.sh/v115/axios@1.3.5/esnext/axios.mjs:679:3
```

## Expected behavior

No errors if the same function is served with deno directly, ie.
```bash
deno run --allow-net supabase/functions/hello/index.ts
```

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

related https://github.com/hwchase17/langchainjs/issues/633

**Comment by andreespirela** [comment]
Investigating

**Comment by andreespirela** [comment]
```
var _ = class {
    constructor(t) {
        t && this.set(t)
    }
    set(t, r, n) {
        let o = this;

        function s(c, d, u) {
            let l = I(d);
            if (!l) throw new Error("header name must be a non-empty string");
            let p = a.findKey(o, l);
            (!p || o[p] === void 0 || u === !0 || u === void 0 && o[p] !== !1) && (o[p || d] = Y(c))
        }
        let i = (c, d) => a.forEach(c, (u, l) => s(u, l, d));
        return a.isPlainObject(t) || t instanceof this.constructor ? i(t, r) : a.isString(t) && (t = t.trim()) && !Vt(t) ? i(Ie(t), r) : t != null && s(r, t, n), this
    }
    get(t, r) {
        if (t = I(t), t) {
            let n = a.findKey(this, t);
            if (n) {
                let o = this[n];
                if (!r) return o;
                if (r === !0) return Jt(o);
                if (a.isFunction(r)) return r.call(this, o, n);
                if (a.isRegExp(r)) return r.exec(o);
                throw new TypeError("parser must be boolean|regexp|function")
            }
        }
    }
    has(t, r) {
        if (t = I(t), t) {
            let n = a.findKey(this, t);
            return !!(n && this[n] !== void 0 && (!r || fe(this, this[n], n, r)))
        }
        return !1
    }
    delete(t, r) {
        let n = this,
            o = !1;

        function s(i) {
            if (i = I(i), i) {
                let c = a.findKey(n, i);
                c && (!r || fe(n, n[c], c, r)) && (delete n[c], o = !0)
            }
        }
        return a.isArray(t) ? t.forEach(s) : s(t), o
    }
    clear(t) {
        let r = Object.keys(this),
            n = r.length,
            o = !1;
        for (; n--;) {
            let s = r[n];
            (!t || fe(this, this[s], s, t, !0)) && (delete this[s], o = !0)
        }
        return o
    }
    normalize(t) {
        let r = this,
            n = {};
        return a.forEach(this, (o, s) => {
            let i = a.findKey(n, s);
            if (i) {
                r[i] = Y(o), delete r[s];
                return
            }
            let c = t ? Kt(s) : String(s).trim();
            c !== s && delete r[s], r[c] = Y(o), n[c] = !0
        }), this
    }
    concat(...t) {
        return this.constructor.concat(this, ...t)
    }
    toJSON(t) {
        let r = Object.create(null);
        return a.forEach(this, (n, o) => {
            n != null && n !== !1 && (r[o] = t && a.isArray(n) ? n.join(", ") : n)
        }), r
    } [Symbol.iterator]() {
        return Object.entries(this.toJSON())[Symbol.iterator]()
    }
    toString() {
        return Object.entries(this.toJSON()).map(([t, r]) => t + ": " + r).join(`
`)
    }
    get[Symbol.toStringTag]() {
        return "AxiosHeaders"
    }
    static from(t) {
        return t instanceof this ? t : new this(t)
    }
    static concat(t, ...r) {
        let n = new this(t);
        return r.forEach(o => n.set(o)), n
    }
    static accessor(t) {
        let n = (this[qe] = this[qe] = {
                accessors: {}
            }).accessors,
            o = this.prototype;

        function s(i) {
            let c = I(i);
            n[c] || (Wt(o, i), n[c] = !0)
        }
        return a.isArray(t) ? t.forEach(s) : s(t), this
    }
};
_.accessor(["Content-Type", "Content-Length", "Accept", "Accept-Encoding", "User-Agent", "Authorization"]);
```

I think this might actually have to do with the way the module is loaded. Maybe some scoping with `var`...
@laktek Seems strange, will try to get a reproducible/smaller example

**Comment by thorwebdev** [comment]
For axios I believe we need the `xhr` ployfill still:  `import "https://deno.land/x/xhr@0.2.1/mod.ts";`

e.g. the openai api packages uses axios and therefore requires the polyfill: https://github.com/supabase-community/deno-fresh-openai-doc-search/blob/main/tools/generate-embeddings.ts

**Comment by thorwebdev** [comment]
Oh, but interesting that it's working when run with Deno directly, hmm

**Comment by nfcampos** [comment]
@thorwebdev note the xhr polyfill shouldn't be needed if a custom axios adapter is used (eg. a fetch-based adapter, like we do in https://github.com/hwchase17/langchainjs)

**Comment by andreespirela** [comment]
If I change the `accessor` field manually from the cached dep and I named it `accessors` or some other name that's not `accessor`. this happens:
```
    static accessors(t) {
        let n = (this[qe] = this[qe] = {
            accessors: {}
        }).accessors, o = this.prototype;
        function s(i) {
            let c = I(i);
            n[c] || (Wt(o, i), n[c] = !0);
        }
        return a.isArray(t) ? t.forEach(s) : s(t), this;
    }
} [Function: accessors]

```

`static` keyword is preserved.

**Comment by laktek** [comment]
This should be fixed in latest version of Edge Runtime. Check example #77

**Comment by laktek** [comment]
Supabase CLI 1.52.3+ should include the Edge Runtime with the fix.

**Comment by liamcharmer** [comment]
Sorry if this is the incorrect location but is this error related to this??

```
TypeError: t is not a function
    at Ke.exports (https://esm.sh/v120/axios@0.26.1/esnext/axios.mjs:3:5734)
    at T.request (https://esm.sh/v120/axios@0.26.1/esnext/axios.mjs:3:9122)
    at Function.request (https://esm.sh/v120/axios@0.26.1/esnext/axios.mjs:2:839)
    at https://esm.sh/v120/openai@3.2.1/esnext/openai.mjs:2:3794
    at https://esm.sh/v120/openai@3.2.1/esnext/openai.mjs:2:26914
    at async n._fn (https://esm.sh/v120/p-retry@4.6.2/esnext/p-retry.mjs:2:1577)
    
    ```

**Comment by andreespirela** [comment]
@liamcharmer can you open a new ticket?

**Comment by liamcharmer** [comment]
> @liamcharmer can you open a new ticket?

https://github.com/supabase/edge-runtime/issues/85 apologies!
