### ISSUE TITLE
Edge Runtime Supabase OpenAI : TypeError: t is not a function

### ISSUE THREAD

**Issue by liamcharmer** [supabase/edge-runtime#85]
So i'm trying to use ConversationalRetrievalQAChain from Langchain within the Edge Functions. However I get the error underneath also. Im unsure if it's axios problem within the edge functions? 
```
const chain = ConversationalRetrievalQAChain.fromLLM(
        model,
        supaStore.asRetriever(null, { chatbots: `%${body.bot}%` }),
        {
          qaTemplate: contextprompt,
          returnSourceDocuments: true,
        }
      );
      console.log("about to chain call");
      const res = await chain.call({
        question: body.user_message,
        chat_history: [],
      });
```

```
TypeError: t is not a function
    at Ke.exports (https://esm.sh/v120/axios@0.26.1/esnext/axios.mjs:3:5734)
    at T.request (https://esm.sh/v120/axios@0.26.1/esnext/axios.mjs:3:9122)
    at Function.request (https://esm.sh/v120/axios@0.26.1/esnext/axios.mjs:2:839)
    at https://esm.sh/v120/openai@3.2.1/esnext/openai.mjs:2:3794
    at https://esm.sh/v120/openai@3.2.1/esnext/openai.mjs:2:26914
    at async n._fn (https://esm.sh/v120/p-retry@4.6.2/esnext/p-retry.mjs:2:1577)```

**Comment by laktek** [comment]
@liamcharmer Are you importing `https://deno.land/x/xhr@0.1.0/mod.ts` as shown in the example here https://github.com/supabase/edge-runtime/blob/main/examples/axios/index.ts#L1

Full example for the function code would be handy for us to reproduce the error.

**Comment by liamcharmer** [comment]
So I gave this a go from reading that post but no luck! I made sure to upgrade the supabase CLI as well

```
import { serve } from "http/server.ts";
import { ChatOpenAI } from "langchain/chat_models/openai";
import { CallbackManager } from "langchain/callbacks";
import {
  ChatPromptTemplate,
  HumanMessagePromptTemplate,
} from "langchain/prompts";
import { OpenAIEmbeddings } from "langchain/embeddings/openai";
import {
  RetrievalQAChain,
  VectorDBQAChain,
  LLMChain,
  ConversationalRetrievalQAChain,
} from "langchain/chains";
import { SupabaseVectorStore } from "langchain/vectorstores/supabase";

import { createClient } from "@supabase/supabase-js";
import { OpenAI, PromptLayerOpenAI } from "langchain/llms/openai";

import { corsHeaders } from "../_shared/cors.ts";


serve(async (req) => {
  // This is needed if you're planning to invoke your function from a browser.
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const body = await req.json();
    const client = createClient(
      Deno.env.get("SUPA_URL"),
      Deno.env.get("SUPA_SECRET_KEY")
    );
    // Check if the request is for a streaming response.
    const streaming = req.headers.get("accept") === "text/event-stream";
    if (body) {
      
      const model = new PromptLayerOpenAI({
        temperature: 0,
        openAIApiKey: AIApiKey,
        promptLayerApiKey: Deno.env.get("PROMPTLAYER_API_KEY"),
        verbose: true,
        callbacks: [
          {
            handleLLMStart: async (llm, prompts) => {
              let object = {
                llm: llm,
                prompts: prompts,
              };
              const updateMessage = await client
                .from("messages")
                .update({
                  llm_start: object,
                })
                .eq("id", body.id);
            },
            handleLLMEnd: async (output) => {
              const updateMessage = await client
                .from("messages")
                .update({
                  llm_end: output,
                })
                .eq("id", body.id);
            },
            handleLLMError: async (err) => {
              const updateMessage = await client
                .from("messages")
                .update({
                  llm_error: err,
                })
                .eq("id", body.id);
            },
          },
        ],
      });
      const supaStore = await SupabaseVectorStore.fromExistingIndex(
        new OpenAIEmbeddings({ openAIApiKey: AIApiKey }),
        {
          client,
          tableName: "embeddings_openai",
          queryName: "match_documents_openai_with_filters",
        }
      );

      let contextprompt =
        "Use the following pieces of context to answer the question at the end as detailed ( four sentences minimum and provide a numbered list if possible) and as long as you can. If you don't know the answer, just say that you don't know, don't try to make up an answer. Do not use external sources or anything else, only the context below. f the question is not related to the context respond that your are only able to answer questions related to the context. If you don't know the answer to the question do not try to make one up. \n\n _________________________\n\n{context}\n\n_________________________ \nQuestion to answer: {question}\nHelpful Answer:";
      console.log("About to chain");
      const chain = ConversationalRetrievalQAChain.fromLLM(
        model,
        supaStore.asRetriever(null, { chatbots: `%${body.bot}%` }),
        {
          qaTemplate: contextprompt,
          returnSourceDocuments: true,
        }
      );
      console.log("about to chain call");
      const res = await chain.call({
        question: body.user_message,
        chat_history: [],
      });

      console.log("about to update message");
      const updateMessage = await client
        .from("messages")
        .update({
          bot_reply: res.text,
          replied_at: new Date(),
          sources: res.sourceDocuments,
        })
        .eq("id", body.id);

        

      return new Response(JSON.stringify(res), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
      if (streaming) {
        console.log("Streaming");
        // For a streaming response we need to use a TransformStream to
        // convert the LLM's callback-based API into a stream-based API.
        const encoder = new TextEncoder();
        const stream = new TransformStream();
        const writer = stream.writable.getWriter();

        const llm = new ChatOpenAI({
          streaming,
          callbackManager: CallbackManager.fromHandlers({
            handleLLMNewToken: async (token) => {
              await writer.ready;
              await writer.write(encoder.encode(`data: ${token}\n\n`));
            },
            handleLLMEnd: async () => {
              await writer.ready;
              await writer.close();
            },
            handleLLMError: async (e) => {
              await writer.ready;
              await writer.abort(e);
            },
          }),
        });
        const chain = new LLMChain({ prompt, llm });
        // We don't need to await the result of the chain.run() call because
        // the LLM will invoke the callbackManager's handleLLMEnd() method
        chain.call({ input }).catch((e) => console.error(e));

        return new Response(stream.readable, {
          headers: { ...corsHeaders, "Content-Type": "text/event-stream" },
        });
      } else {
        console.log("Not streaming");
        // For a non-streaming response we can just await the result of the
        // chain.run() call and return it.
        const llm = new ChatOpenAI();
        const chain = new LLMChain({ prompt, llm });
        const response = await chain.call({ input });

        return new Response(JSON.stringify(response), {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
    }
  } catch (e) {
    console.log(e);
    return new Response(JSON.stringify({ error: e.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});

```

**Comment by liamcharmer** [comment]
``` {
  "imports": {
    "http/": "https://deno.land/std@0.177.0/http/",
    "@supabase/supabase-js": "https://esm.sh/@supabase/supabase-js@2.15.0",
    "langchain/": "https://esm.sh/langchain@0.0.73/"
  }
}
```

**Comment by laktek** [comment]
Can you try adding `import "https://deno.land/x/xhr@0.1.0/mod.ts";` as the first import in your function?

**Comment by liamcharmer** [comment]
Oh @laktek fml im so sorry, that worked thank you so so much

**Comment by laktek** [comment]
Glad it worked :) Will close this issue.
